name: Bug or regression
description: Report a bug or regression in the application.
body:
  - type: textarea
    id: current-state
    attributes:
      label: Current state
      description: Describe the current behavior of the application.

  - type: textarea
    id: background
    attributes:
      label: Background
      description: Provide any relevant background information.

  - type: textarea
    id: desired-state
    attributes:
      label: Desired state
      description: Describe the behavior you expect.

  - type: textarea
    id: implementation-details
    attributes: 
      label: Implementation details
      description: Outline potential solutions or implementation details.

  - type: textarea
    id: related-work
    attributes:
      label: Related work
      description: List any related work (e.g., publishing checks, localization, docs, comms).

  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: Define the scope of the issue.

  - type: textarea
    id: test-scenario
    attributes:
      label: Test scenario
      description: Provide a test scenario to validate the fix.

  - type: textarea
    id: reference
    attributes: 
      label: Reference
      description: Add any links or references relevant to the issue.
