name: Feature or enhancement
description: Suggest a new feature or enhancement.
body:
  - type: textarea
    id: user-statement
    attributes: 
      label: User statement
      description: Who is this feature for? What problem does it solve?

  - type: textarea
    id: background
    attributes:
      label: Background 
      description: Provide any relevant background information.

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed solution
      description: Describe the proposed solution or feature.

  - type: textarea
    id: implementation-details
    attributes:
      label: Implementation details
      description: Outline potential solutions or implementation details.

  - type: textarea
    id: related-work
    attributes:
      label: Related work
      description: List any related work (e.g., publishing checks, localization, docs, comms).

  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: Define the scope of the issue.

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance criteria
      description: List the criteria that must be met for the feature to be considered complete.

  - type: textarea
    id: reference
    attributes:
      label: Reference
      description: Add any links or references relevant to the feature.

  - type: textarea
    id: problem-description
    attributes:
      label: Summary 
      description: Required. Describe the problem. Include links to specific topics where the problem exists, if applicable.
    validations:
      required: true
      
  - type: checkboxes
    id: terms-public
    attributes:
      label: Public issues must not contain sensitive information
      description: Required. Examples of sensitive information include but are not limited to customer information, employee information, unreleased features, release dates, or confidential product information.
      options:
        - label: This issue contains no sensitive information. 
          required: true
